# This is the default format.
# For more see: https://github.com/mojombo/jekyll/wiki/Permalinks
permalink: /:categories/:year/:month/:day/:title

exclude: [".rvmrc", ".rbenv-version", "ReadMe.md", "Rakefile", "changelog.md", "License.md"]
highlighter: rouge

markdown: kramdown


theme: jekyll-theme-minimal

title : How to write academic papers: exercises and guidelines
author :
  name : Florian M. Hollenbach 
  email : fhollenbach@tamu.edu
  github : fhollenbach
  twitter : fhollenbach
  feedburner : nil



production_url : https://fhollenbach.github.io/WritingAcademic

JB :
  version : 0.3.0